import Head from 'next/head';
import Link from 'next/link';
import {
  Button,
  Col, Container, ListGroup, Row,
} from 'react-bootstrap';
import Navigation from '../components/header';
import Hero from '../components/hero';
import ContactSection from '../components/contact';
import DurableSection from '../components/durable';
import ProdukterSection from '../components/produkter';
import BenefitsSection from '../components/benefits';
import RecensionSection from '../components/recensionSection';
import Footer from '../components/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Wängkraft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero/>
        <ContactSection></ContactSection>
        <BenefitsSection></BenefitsSection>
        <ProdukterSection></ProdukterSection>
        <DurableSection></DurableSection>
        <RecensionSection></RecensionSection>
      </main>
    </>
  );
}
